version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mypasswd
    networks:
      - n8n
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    networks:
      - n8n

  n8n-main:
    image: n8nio/n8n
    restart: always
    env_file:
      - .n8n/queue.env
    ports:
      - "5678:5678"
    networks:
      - n8n

  n8n-worker1:
    image: n8nio/n8n
    restart: always
    command: worker
    env_file:
      - .n8n/queue.env
    networks:
      - n8n

  n8n-worker2:
    image: n8nio/n8n
    restart: always
    command: worker
    env_file:
      - .n8n/queue.env
    networks:
      - n8n

  n8n-webhook:
    image: n8nio/n8n
    restart: always
    command: webhook
    env_file:
      - .n8n/queue.env
    networks:
      - n8n

volumes:
  pgdata:

networks:
  n8n:
